{% set version = "0.8.2" %}

package:
  name: toolz
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/toolz/toolz-{{ version }}.tar.gz
  sha256: 4a13c90c426001d6299c5568cf5b98e095df9c985df194008a67f84ef4fc6c50
  patches:
    # https://github.com/pytoolz/toolz/pull/405
    - backport_405.patch

build:
  number: 3
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - toolz
    - toolz.curried
    - toolz.functoolz
    - toolz.sandbox

about:
  home: http://toolz.readthedocs.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: A functional standard library for Python

extra:
  recipe-maintainers:
    - mrocklin
    - eriknw
    - jcrist
    - jakirkham
    - ocefpaf
