{% set name = "toolz" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/toolz-{{ version }}.tar.gz
  sha256: 2c86e3d9a04798ac556793bced838816296a2f085017664e4995cb40a1047a02

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - tlz
    - toolz
    - toolz.curried
    - toolz.functoolz
    - toolz.sandbox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://toolz.readthedocs.org/
  summary: A functional standard library for Python
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jrbourbeau
    - mrocklin
    - eriknw
    - jcrist
    - jakirkham
    - ocefpaf
