{% set name = "toolz" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/toolz-{{ version }}.tar.gz
  sha256: 9667a038e9d6ecba37995e26cb2f59ec6420b6ad8dd9677de59db9b956b08490

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77
    - setuptools-git-versioning >=2.0
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - tlz
    - toolz
    - toolz.curried
    - toolz.functoolz
    - toolz.sandbox
  commands:
    - pip check
    - 'python -c "import toolz; assert toolz.__version__ != ''0.0.0''"'
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://toolz.readthedocs.org/
  summary: A functional standard library for Python
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hendrikmakait
    - jrbourbeau
    - mrocklin
    - eriknw
    - jcrist
    - jakirkham
    - ocefpaf
