travis:
  secure:
    BINSTAR_TOKEN: e4pjxpXt2977AQXJ1hLbvrqFaQ6I+7yIe9Y9mSNJisEoQ66y6lZJUnaaFWswcRwZf6s+C+Bj8dQb0fqC4gDfBiimR1xKj3WQ0kEMR9QOmIgth9EAV+AA3YLU/dHLVjisTYpnleq3CCmqXfE0Ph0xIruCk+rWNP3EH2kjFp45XammrhyhqNy4mRKlSeX5c72BzzWVpUqx3fSeDGWwIatVQwAWCBhzP67JLWabjJb/tWHfYP8LcMwaQ3yPq0b3Bb89Vi5K0ukZblIRgtDZz/WX5bggnrFhHjU+oddb+WRv8QDn/hQEalQxHQD3CDJig3L4fxyNtaWWXg+0OWKuGQW/dr8xG7z/suJ0XJAoM4LFOYuebuv+5vD5owzCtdFvVpo4iBDU024r3SDdbzz10DrYB3VgUrNoRFFJKrljEFm9mXTcAe9w8CCZn20K0n4AN6Eybh3KoiBBOUzugrj7iBD2NAeQ9Y+12P8OyxbIrVO/yPphTO1eu4Wt2Kb2+8UujLH44YH/BS9JQj5e3qTiegqyxjPkSirRTD9GU6Xpe1/E97k+fjI1+YJb/GET5ngHY1EKtV9t9XXMmvvTO3QZBVL2qZfWCfNCH//VoDw9FA2SuuXpwmsbGSMrCkYx7TKh6180b7DiYiiVlv+WJpi1T+Z0zUuQ1W0zZWnLaFNwMF4PjME=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
